### ISSUE TITLE
Organização e qualidade de código na execução do IO

### ISSUE THREAD

**Issue by jg-lo** [joaoandrepestre/Sistemas-Operacionais#2]
A função que simula a execução de uma função pelo IO pode ter sua qualidade melhorada para uma com maior legibilidade e organização.

**Comment by joaoandrepestre** [comment]
Tentei reorganizar e tornar genérica. Agora a função executa apenas um tipo de IO por vez e é chamada 3 vezes na main. Isso fez com que a função precisasse de switchs para definir tempos e fazer prints. Se estiver satisfatório, podemos fechar esse issue
